IdeasBoard/Controllers/AdministrationController.cs
using IdeasBoard.Models;
using IdeasBoard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IdeasBoard.Controllers
{
    public class AdministrationController : Controller
    {
        private ApplicationDbContext context;       

        public AdministrationController()
        {
            context = new ApplicationDbContext();
        }

        [Authorize(Roles = "Owner,Admin")]
        public ActionResult UsersWithRoles()
        {
            ViewBag.UserColumns = new List<string> { "Name", "Email", "Role" };
            var usersWithRoles = (from user in context.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      Name = user.Name,
                                      Email = user.Email,
                                      Roles= (from userRole in user.Roles
                                                   join role in context.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => 
                                  new UserRoleViewModel()
                                  {
                                      UserId = p.UserId,
                                      Name = p.Name,
                                      Email = p.Email,
                                      Role = string.Join(",", p.Roles)
                                  });

            return View(usersWithRoles);
        }
    }
}

IdeasBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">

    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/datatables.css">
</head>
<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light ">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item nav-link">
                            @Html.ActionLink("Ideas", "Index", "Ideas")
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Owner") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu">
                                    @Html.ActionLink("Users", "UsersWithRoles", "Administration", null, new { @class = "dropdown-item" })
                                </div>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="mt-5 container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ideas Board</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/datatables.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>