IdeasBoard/Models/Idea.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IdeasBoard.Models
{
    public class Idea
    {
        public int IdeaID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public int ImageIndex { get; set; }
        public string Description { get; set; }
        public string Supplies { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ApprovedAt { get; set; }
        public string ApproveMessage { get; set; }

        public virtual ApplicationUser User{get; set;}
        public virtual ICollection<Vote> Votes { get; set; }
    }
}

IdeasBoard/Models/Vote.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace IdeasBoard.Models
{
    public class Vote
    {
        public int VoteID { get; set; }
        [Index("IX_UserAndIdea", 1, IsUnique = true)]
        public string UserID { get; set; }
        [Index("IX_UserAndIdea", 2, IsUnique = true)]
        public int IdeaID { get; set; }
        public DateTime VotedOn { get; set; }

        public virtual ApplicationUser User { get; set; }
        public virtual Idea Idea { get; set; }
    }
}

IdeasBoard/ViewModels/IdeaViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace IdeasBoard.ViewModels
{
    public class IdeaViewModel
    {
        [Required]
        [Display(Name = "Idea name")]
        [StringLength(30, ErrorMessage = "The {0} must be at minimum {2} and maximum 30 characters long.", MinimumLength = 3)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Supplies")]
        public string Supplies { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

IdeasBoard/ViewModels/VoteViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace IdeasBoard.ViewModels
{
    public class VoteViewModel
    {
        public int IdeaID { get; set; }
        public string OwnerName { get; set; }
        public string Name { get; set; }
        public int VoteCount { get; set; }
        public DateTime CreatedAt { get; set; }          
        public DateTime? ApprovedAt { get; set; }          
        public bool Voted { get; set; }

    }
}

IdeasBoard/Controllers/IdeasController.cs
using IdeasBoard.Models;
using IdeasBoard.Utilities;
using IdeasBoard.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IdeasBoard.Controllers
{
    public class IdeasController : Controller
    {
        private ApplicationUserManager _userManager;

        private ApplicationDbContext context;

        public IdeasController()
        {
            context = new ApplicationDbContext();
        }      

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }


        // GET: Ideas
        [Authorize]
        public ActionResult Index()
        {
            return View(context.Ideas.Include(i => i.Votes).ToList());
        }

        // GET: Ideas/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int id=0)
        {
            try
            {
                Idea idea = await context.Ideas.FindAsync(id);

                if (idea == null) return RedirectToAction("Index");

               ICollection<ApplicationUser> users = UserManager.Users.ToList();
               ApplicationUser owner = (from user 
                                        in users
                                        where user.Id == idea.UserID
                                        select user)
                                        .FirstOrDefault();

                ICollection<IdeaUserDetails> usersWhoVoted = (from user
                                                              in users
                                                              where idea.Votes.Any(vote => vote.UserID == user.Id)
                                                              select new IdeaUserDetails
                                                              {
                                                                  UserName = user.Name,
                                                                  VotedOn = DateTime.Now

                                                              }).ToList();

                IdeaDetailsViewModel ideaDetailsModel = new IdeaDetailsViewModel
                {
                    IdeaID = idea.IdeaID,
                    Name = idea.Name,
                    Description = idea.Description,
                    OwnerName = owner.Name,
                    OwnerEmail = owner.Email,
                    Supplies = idea.Supplies,
                    VoteCount = idea.Votes.Count(),
                    UsersWhoVoted = usersWhoVoted,
                    CreatedAt = idea.CreatedAt,
                    ApprovedAt = idea.ApprovedAt
                };
            return View(ideaDetailsModel);

            }
            catch(Exception ex)
            {
                Log.Error("Error while retriving idea details!", ex);
                return RedirectToAction("Index");
            }   

        }

        // GET: Ideas/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ideas/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IdeaViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

                    if (user == null) return RedirectToAction("Index");

                    Random random = new Random();
                    int imageIndex = random.Next(1, 5);

                    context.Ideas.Add(new Idea { UserID = user.Id, Name = model.Name, Supplies = model.Supplies, Description = model.Description, ImageIndex = imageIndex, CreatedAt = DateTime.Now });

                    await context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    Log.Error("Error while creating idea!", ex);
                    return RedirectToAction("Index");
                }
               
            }
           
             return View(model);
            
        }

        // GET: Ideas/Edit/5
        [Authorize(Roles = "Owner")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ideas/Edit/5
        [HttpPost]
        [Authorize(Roles = "Owner")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ideas/Approve/5
        [Authorize(Roles = "Owner, Admin")]
        public ActionResult Approve(int id)
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Owner, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Approve(int id, FormCollection collection)
        {
            return View();
        }

        // GET: Ideas/Delete/5
        [Authorize(Roles = "Owner, Admin")]
        public async Task<ActionResult> Delete(int id=0)
        {
            try
            {
                Idea idea = await context.Ideas.FindAsync(id);

                if (idea == null) return RedirectToAction("Index");

                ICollection<ApplicationUser> users = UserManager.Users.ToList();
                ApplicationUser owner = (from user
                                         in users
                                         where user.Id == idea.UserID
                                         select user)
                                         .FirstOrDefault();
                

                IdeaDetailsViewModel ideaDetailsModel = new IdeaDetailsViewModel
                {
                    IdeaID = idea.IdeaID,
                    Name = idea.Name,
                    OwnerName = owner.Name,
                    CreatedAt = idea.CreatedAt,
                    ApprovedAt = idea.ApprovedAt
                };
                return View(ideaDetailsModel);

            }
            catch (Exception ex)
            {
                Log.Error("Error while retriving idea details!", ex);
                return RedirectToAction("Index");
            }
        }

        // POST: Ideas/Delete/5
        [HttpPost]
        [Authorize(Roles = "Owner, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                Idea idea = await context.Ideas.Where(_idea => _idea.IdeaID == id).FirstOrDefaultAsync();
                if (idea != null)
                {
                    context.Ideas.Remove(idea);
                    await context.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Log.Error("Could not delete the selected idea!", ex);
                return RedirectToAction("Index");
            }
        }


        // GET: Ideas/Vote/5
        [Authorize]
        public async Task<ActionResult> Vote(int id = 0)
        {
            try
            {
                Idea idea = await context.Ideas.FindAsync(id);

                if (idea == null) return RedirectToAction("Index");

                ApplicationUser owner = await UserManager.Users.Where(_user => _user.Id == idea.UserID).FirstOrDefaultAsync();

                ApplicationUser userWhoVoated = await UserManager.FindByIdAsync(User.Identity.GetUserId());

                Vote vote = await context.Votes.Where(_vote => _vote.UserID == userWhoVoated.Id && _vote.IdeaID == idea.IdeaID).FirstOrDefaultAsync();

                VoteViewModel voteViewModel = new VoteViewModel
                {
                    IdeaID = idea.IdeaID,
                    Name = idea.Name,
                    OwnerName = owner.Name,
                    CreatedAt = idea.CreatedAt,
                    ApprovedAt = idea.ApprovedAt,
                    Voted = (vote != null) ? true : false                    
                };
                return View(voteViewModel);

            }
            catch (Exception ex)
            {
                Log.Error("Error while retriving vote details!", ex);
                return RedirectToAction("Index");
            }
        }

        // POST: Ideas/Vote/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Vote(int id, FormCollection collection)
        {
            try
            {
                Idea idea = await context.Ideas.FindAsync(id);

                if (idea == null) return RedirectToAction("Index");

                ApplicationUser userWhoVoated = await UserManager.FindByIdAsync(User.Identity.GetUserId());

                Vote vote = await context.Votes.Where(_vote => _vote.UserID == userWhoVoated.Id && _vote.IdeaID == idea.IdeaID).FirstOrDefaultAsync();

                if (vote == null)
                {
                    context.Votes.Add(new Vote { UserID = userWhoVoated.Id, IdeaID = idea.IdeaID });
                    await context.SaveChangesAsync();
                }
                else
                {
                    Log.Warning("You alredy voated!");
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

IdeasBoard/Views/Ideas/Approve.cshtml
@model IdeasBoard.Models.Idea

@{
    ViewBag.Title = "Approve";
}

<h2>Approve</h2>

IdeasBoard/Views/Ideas/Create.cshtml
@model IdeasBoard.ViewModels.IdeaViewModel

@{
    ViewBag.Title = "Create new Idea";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <div class="row">
        <div class="col-sm">
             <h2>@ViewBag.Title</h2>
        </div>
        <div class="col-sm">
            <h2 align="right">@Html.ActionLink("Back to Idea board", "Index", "Ideas", null, new { @class = "btn btn-primary" })</h2>
        </div>    
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Supplies, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Supplies, new { cols = "40", rows = "2" , @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Supplies, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description, new { cols = "40", rows = "6" , @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="Create" class="col-md-4 btn btn-primary" />
        </div>
    </div>

</div>
}

IdeasBoard/Views/Ideas/Delete.cshtml
@model IdeasBoard.ViewModels.IdeaDetailsViewModel

@{
    ViewBag.Title = "Delete idea";
}

<h3>Are you sure you want to delete <b class="red">@Html.DisplayFor(model => model.Name)</b>?</h3>
<p>Created by: @Html.DisplayFor(model => model.OwnerName) </p> 


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
    </div>
}

IdeasBoard/Views/Ideas/Details.cshtml
@using System.Linq
@model IdeasBoard.ViewModels.IdeaDetailsViewModel

@{
    ViewBag.Title = "Idea details";
}


<div class="row">
    <div class="col-sm">
        <h2 align="right">@Html.ActionLink("Back to Ideas", "Index", "Ideas", null, new { @class = "btn btn-primary" })</h2>
    </div>
</div>
<hr />

<div class="row">
    <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Users who voated</span>
            <span class="badge badge-secondary badge-pill">@Html.DisplayFor(model => model.VoteCount)</span>
        </h4>
        @if (Model.UsersWhoVoted.Any())
        {
            <div id="users">
                <ul class="list list-group mb-3">
                    @foreach (var user in Model.UsersWhoVoted)
                    {
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">@user.UserName</h6>
                            <small class="text-muted">@user.VotedOn</small>
                        </div>
                    </li>
                    }
                </ul>
                <ul class="pagination"></ul>
            </div>
        }
        else
        {
            <ul class="list list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="Name my-0">Nobbody voted yet!</h6>
                    </div>
                </li>
            </ul>
        }
    </div>
    <div class="col-md-8 order-md-1">
        <div class="card">
            <div class="card-header text-center">
                <h3>@Html.DisplayFor(model => model.Name)</h3>
                @if (Model.ApprovedAt != null)
                {
                    <h5 class="green mb-0">approved!</h5>
                }
                else
                {
                    <h5 class="red mb-0">not approved yet!</h5>
                }
            </div>
            <div class="card-body">
                <p class="card-text">@Html.DisplayFor(model => model.Description)</p>
                <hr />
                <h6 class="card-text">Needed:  @Html.DisplayFor(model => model.Supplies)</h6>
            </div>
            <div class="card-footer text-muted">
                <div class="row">
                    <div class="col-sm">
                        <p class="mb-0">Created by: <b>@Html.DisplayFor(model => model.OwnerName)</b></p>
                    </div>
                    <div class="col-sm">
                        <p align="right" class="mb-0">@Html.DisplayFor(model => model.CreatedAt)</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="ml-auto mt-2 col-sm-4">
                @Html.ActionLink("Vote", "Vote", "Ideas", new { id = Model.IdeaID }, new { @class = "btn btn-success btn-block" })
            </div>
        </div>
    </div>
</div>
@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("Owner"))
    {
        <hr />      
        <div class="row">
            <div class="mt-2 col-sm-2">
                @Html.ActionLink("Approve", "Approve", "Ideas", new { id =Model.IdeaID}, new { @class = "btn btn-success btn-block" })
            </div>
            <div class="mt-2 col-sm-2">
                @Html.ActionLink("Delete", "Delete", "Ideas", new { id = Model.IdeaID }, new { @class = "btn btn-primary btn-block" })
            </div>
        </div>
    }
}



@section Scripts {
    @Scripts.Render("~/Scripts/List.js");
    <script>
        var options = {
            valueNames: [
                'Name',
                'Datetime'
            ],
            page: 5,
            pagination: true
        };
        var userList = new List('users', options);
    </script>
}

IdeasBoard/Views/Ideas/Index.cshtml
@using System.Linq
@model IEnumerable<IdeasBoard.Models.Idea>

@{
    ViewBag.Title = "Ideas board";
}

<div class="row">
    <div class="col-sm">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-sm">
        <h2 align="right">@Html.ActionLink("Create your Idea", "Create", "Ideas", null, new { @class = "btn btn-primary" })</h2>
    </div>
</div>
<hr>

<div class="container idea-gallery-container">
    <div class="idea-gallery">
        <div class="row">
            @if (Model.Any())
            {
                foreach (var idea in Model)
                {
                    <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                            <div class="idea-box">
                                <a class="lightbox" href="@Url.Action("Details", "Ideas", new { id = idea.IdeaID })">
                                    <img class="img-fluid" src="~/Content/Images/Notes_@(idea.ImageIndex).png" alt="">
                                </a>
                                <h3 class="idea-text">@idea.Name</h3>
                            </div>
                            <div class="caption">
                                @if (idea.Description.Length > 50)
                                {
                                    <p>@(idea.Description.Substring(0, 50))...</p>
                                }
                                else
                                {
                                    <p>@idea.Description</p>
                                }
                                <h3 class="text-color">Votes: <b>@idea.Votes.Count()</b></h3>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-sm">
                    <h3 align="center" class="text-color">There's no single idea!</h3>
                </div>
            }
        </div>
    </div>
</div>

IdeasBoard/Views/Ideas/Vote.cshtml
@model IdeasBoard.ViewModels.VoteViewModel

@{
    ViewBag.Title = "Vote";
}

<div class="row">
    <div class="col-sm">
        <h2 align="right">@Html.ActionLink("Back to Ideas", "Index", "Ideas", null, new { @class = "btn btn-primary" })</h2>
    </div>
</div>
<hr />

@if (Model.Voted)
{
    <h4>You aleready voated for the idea <b class="red">@Html.DisplayFor(model => model.Name)</b>!</h4>
    <p>Created by: <b>@Html.DisplayFor(model => model.OwnerName)</b></p>
}
else
{
    <h4>Are you sure you want to vote for the idea <b class="red">@Html.DisplayFor(model => model.Name)</b>?</h4>
     <p>Created by: <b>@Html.DisplayFor(model => model.OwnerName)</b></p>

    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Vote" class="col-md-1 btn btn-success" />
        </div>
    }

}